services:
  - type: worker
    name: bot-discord-chrono-llm2
    env: python
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: ALERT_CHANNEL_ID
        sync: false
      - key: FIREBASE_CREDENTIALS_B64
        sync: false
